services:
  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./nginx/:/etc/nginx/conf.d

    ports:
      - "8090:80"
    depends_on:
      - main

  main:
    image: &image main
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.40"
          memory: 768M
    restart: always
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8000",
        "--log-level",
        "debug",
        "--log-file=-",
        "--capture-output",
        "--workers",
        "3",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "config.asgi:application",
      ]
    volumes: &volumes
      - ./static:/code/static
      - ./media:/code/media
    env_file: &env_file ./.docker.env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:7-alpine
    command: redis-server --loglevel warning
    volumes:
      - ./redis_data:/data

  celery-beat:
    image: *image
    container_name: celery-beat
    restart: unless-stopped
    env_file: *env_file
    command:
      [
        "celery",
        "-A",
        "config",
        "beat",
        "-l",
        "info",
        "--scheduler",
        "django_celery_beat.schedulers:DatabaseScheduler",
      ]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    volumes: *volumes
    depends_on:
      - redis

  migration:
    image: *image
    env_file: *env_file
    command: /bin/sh -c 'python manage.py migrate && python manage.py collectstatic --noinput'
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
    volumes: *volumes
    depends_on:
      - redis

  celery-worker:
    image: *image

    restart: unless-stopped
    env_file: *env_file
    command:
      ["celery", "-A", "config", "worker", "-l", "DEBUG", "--concurrency", "3"]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 768M
    volumes: *volumes
    depends_on:
      - redis

volumes:
  postgres_data:
